#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 67
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 15

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_use = 2,
  anon_sym_fn = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_LPAREN = 5,
  anon_sym_COMMA = 6,
  anon_sym_RPAREN = 7,
  anon_sym_COLON = 8,
  anon_sym_int = 9,
  anon_sym_float = 10,
  anon_sym_bool = 11,
  anon_sym_str = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_let = 15,
  anon_sym_EQ = 16,
  anon_sym_if = 17,
  anon_sym_else = 18,
  anon_sym_while = 19,
  anon_sym_return = 20,
  anon_sym_PIPE_PIPE = 21,
  anon_sym_AMP_AMP = 22,
  anon_sym_EQ_EQ = 23,
  anon_sym_BANG_EQ = 24,
  anon_sym_LT = 25,
  anon_sym_LT_EQ = 26,
  anon_sym_GT = 27,
  anon_sym_GT_EQ = 28,
  anon_sym_PLUS = 29,
  anon_sym_DASH = 30,
  anon_sym_STAR = 31,
  anon_sym_SLASH = 32,
  anon_sym_BANG = 33,
  anon_sym_as = 34,
  sym_float_literal = 35,
  sym_integer_literal = 36,
  anon_sym_true = 37,
  anon_sym_false = 38,
  sym_string_literal = 39,
  sym_line_comment = 40,
  sym_source_file = 41,
  sym_use_declaration = 42,
  sym_function_definition = 43,
  sym_parameter_list = 44,
  sym_parameter = 45,
  sym_type = 46,
  sym_block = 47,
  sym_statement = 48,
  sym_let_statement = 49,
  sym_assignment_statement = 50,
  sym_if_statement = 51,
  sym_while_statement = 52,
  sym_return_statement = 53,
  sym_expression_statement = 54,
  sym__expression = 55,
  sym_binary_expression = 56,
  sym_unary_expression = 57,
  sym_cast_expression = 58,
  sym_call_expression = 59,
  sym_parenthesized_expression = 60,
  sym_boolean_literal = 61,
  aux_sym_source_file_repeat1 = 62,
  aux_sym_source_file_repeat2 = 63,
  aux_sym_parameter_list_repeat1 = 64,
  aux_sym_block_repeat1 = 65,
  aux_sym_call_expression_repeat1 = 66,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_use] = "use",
  [anon_sym_fn] = "fn",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COLON] = ":",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_bool] = "bool",
  [anon_sym_str] = "str",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_while] = "while",
  [anon_sym_return] = "return",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_BANG] = "!",
  [anon_sym_as] = "as",
  [sym_float_literal] = "float_literal",
  [sym_integer_literal] = "integer_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string_literal] = "string_literal",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_use_declaration] = "use_declaration",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_parameter] = "parameter",
  [sym_type] = "type",
  [sym_block] = "block",
  [sym_statement] = "statement",
  [sym_let_statement] = "let_statement",
  [sym_assignment_statement] = "assignment_statement",
  [sym_if_statement] = "if_statement",
  [sym_while_statement] = "while_statement",
  [sym_return_statement] = "return_statement",
  [sym_expression_statement] = "expression_statement",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_cast_expression] = "cast_expression",
  [sym_call_expression] = "call_expression",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_call_expression_repeat1] = "call_expression_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_str] = anon_sym_str,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_while] = anon_sym_while,
  [anon_sym_return] = anon_sym_return,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_as] = anon_sym_as,
  [sym_float_literal] = sym_float_literal,
  [sym_integer_literal] = sym_integer_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string_literal] = sym_string_literal,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_use_declaration] = sym_use_declaration,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_parameter] = sym_parameter,
  [sym_type] = sym_type,
  [sym_block] = sym_block,
  [sym_statement] = sym_statement,
  [sym_let_statement] = sym_let_statement,
  [sym_assignment_statement] = sym_assignment_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_while_statement] = sym_while_statement,
  [sym_return_statement] = sym_return_statement,
  [sym_expression_statement] = sym_expression_statement,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_cast_expression] = sym_cast_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_call_expression_repeat1] = aux_sym_call_expression_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_str] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_while] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_use_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_let_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_while_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_cast_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_call_expression_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_body = 2,
  field_condition = 3,
  field_consequence = 4,
  field_left = 5,
  field_name = 6,
  field_operand = 7,
  field_operator = 8,
  field_parameters = 9,
  field_path = 10,
  field_return_type = 11,
  field_right = 12,
  field_target = 13,
  field_type = 14,
  field_value = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_path] = "path",
  [field_return_type] = "return_type",
  [field_right] = "right",
  [field_target] = "target",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 4},
  [5] = {.index = 10, .length = 1},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 2},
  [8] = {.index = 15, .length = 2},
  [9] = {.index = 17, .length = 1},
  [10] = {.index = 18, .length = 2},
  [11] = {.index = 20, .length = 3},
  [12] = {.index = 23, .length = 2},
  [13] = {.index = 25, .length = 2},
  [14] = {.index = 27, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_path, 1},
  [1] =
    {field_body, 3},
    {field_name, 1},
    {field_parameters, 2},
  [4] =
    {field_name, 0},
    {field_type, 2},
  [6] =
    {field_body, 5},
    {field_name, 1},
    {field_parameters, 2},
    {field_return_type, 4},
  [10] =
    {field_value, 1},
  [11] =
    {field_operand, 1},
    {field_operator, 0},
  [13] =
    {field_condition, 1},
    {field_consequence, 2},
  [15] =
    {field_body, 2},
    {field_condition, 1},
  [17] =
    {field_name, 0},
  [18] =
    {field_name, 0},
    {field_value, 2},
  [20] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [23] =
    {field_target, 2},
    {field_value, 0},
  [25] =
    {field_name, 1},
    {field_value, 3},
  [27] =
    {field_alternative, 4},
    {field_condition, 1},
    {field_consequence, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 3,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 41,
  [69] = 69,
  [70] = 70,
  [71] = 42,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(10);
      ADVANCE_MAP(
        '!', 32,
        '"', 2,
        '&', 3,
        '(', 12,
        ')', 14,
        '*', 30,
        '+', 27,
        ',', 13,
        '-', 29,
        '/', 31,
        ':', 15,
        '<', 23,
        '=', 18,
        '>', 25,
        '{', 16,
        '|', 7,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '!', 32,
        '"', 2,
        '&', 3,
        '(', 12,
        ')', 14,
        '*', 30,
        '+', 27,
        ',', 13,
        '-', 28,
        '/', 31,
        '<', 23,
        '=', 18,
        '>', 25,
        '{', 16,
        '|', 7,
        '}', 17,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(36);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '&') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '{') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(4);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == '|') ADVANCE(19);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(11);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(22);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'l', 6,
        'r', 7,
        's', 8,
        't', 9,
        'u', 10,
        'w', 11,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(15);
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(24);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(25);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 29:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 32:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_str);
      END_STATE();
    case 34:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 40:
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 46:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_while);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_return);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 4},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 4},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 4},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_str] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_while] = ACTIONS(1),
    [anon_sym_return] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(84),
    [sym_use_declaration] = STATE(51),
    [sym_function_definition] = STATE(58),
    [aux_sym_source_file_repeat1] = STATE(51),
    [aux_sym_source_file_repeat2] = STATE(58),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_use] = ACTIONS(7),
    [anon_sym_fn] = ACTIONS(9),
    [sym_line_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(11), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(13), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [37] = 15,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(31), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(47), 6,
      sym_let_statement,
      sym_assignment_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(23), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [98] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(37), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(39), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [135] = 15,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(41), 1,
      sym_identifier,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      anon_sym_RBRACE,
    ACTIONS(49), 1,
      anon_sym_let,
    ACTIONS(52), 1,
      anon_sym_if,
    ACTIONS(55), 1,
      anon_sym_while,
    ACTIONS(58), 1,
      anon_sym_return,
    ACTIONS(67), 1,
      sym_integer_literal,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(64), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(70), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(47), 6,
      sym_let_statement,
      sym_assignment_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(23), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [196] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(73), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(75), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [233] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(81), 15,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [272] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(83), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(85), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [309] = 15,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      sym_integer_literal,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(31), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(47), 6,
      sym_let_statement,
      sym_assignment_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(23), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [370] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(89), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 15,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_float_literal,
      sym_string_literal,
  [413] = 15,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      sym_integer_literal,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(31), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(5), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(47), 6,
      sym_let_statement,
      sym_assignment_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(23), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [474] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(101), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(103), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [511] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(105), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(107), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [548] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 11,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 13,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      sym_float_literal,
      sym_string_literal,
  [593] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(111), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(113), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [630] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(89), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 9,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      sym_float_literal,
      sym_string_literal,
  [679] = 15,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_let,
    ACTIONS(23), 1,
      anon_sym_if,
    ACTIONS(25), 1,
      anon_sym_while,
    ACTIONS(27), 1,
      anon_sym_return,
    ACTIONS(33), 1,
      sym_integer_literal,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(31), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(11), 2,
      sym_statement,
      aux_sym_block_repeat1,
    STATE(47), 6,
      sym_let_statement,
      sym_assignment_statement,
      sym_if_statement,
      sym_while_statement,
      sym_return_statement,
      sym_expression_statement,
    STATE(23), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [740] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(121), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(123), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [777] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(91), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(89), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [828] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(89), 12,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(91), 16,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
  [867] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(79), 1,
      anon_sym_LPAREN,
    ACTIONS(127), 1,
      anon_sym_EQ,
    ACTIONS(81), 12,
      anon_sym_RBRACE,
      anon_sym_PIPE_PIPE,
      anon_sym_AMP_AMP,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(77), 13,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH,
      anon_sym_BANG,
      anon_sym_as,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [906] = 11,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(131), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(129), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [956] = 11,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(137), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(135), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1006] = 11,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(141), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(139), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1056] = 11,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(97), 1,
      anon_sym_as,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(145), 4,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(143), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      anon_sym_BANG,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1106] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    ACTIONS(155), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(153), 2,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(151), 4,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
    STATE(25), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1149] = 9,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(161), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(159), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(35), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1186] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(165), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(163), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(22), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1220] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(169), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(167), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(24), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1254] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(173), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(171), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(45), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1288] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(177), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(175), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(46), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1322] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(181), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(179), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(6), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1356] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(185), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(183), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(20), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1390] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(189), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(187), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(49), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1424] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_RPAREN,
    ACTIONS(195), 1,
      anon_sym_as,
    STATE(65), 1,
      aux_sym_call_expression_repeat1,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1466] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(199), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(197), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(10), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1500] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(203), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(201), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(14), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1534] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(207), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(205), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(16), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1568] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(211), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(209), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(19), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1602] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(215), 1,
      sym_integer_literal,
    ACTIONS(29), 2,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(35), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(213), 2,
      sym_float_literal,
      sym_string_literal,
    STATE(43), 7,
      sym__expression,
      sym_binary_expression,
      sym_unary_expression,
      sym_cast_expression,
      sym_call_expression,
      sym_parenthesized_expression,
      sym_boolean_literal,
  [1636] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(219), 6,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(217), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1659] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(223), 6,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(221), 9,
      anon_sym_let,
      anon_sym_if,
      anon_sym_else,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1682] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(195), 1,
      anon_sym_as,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(225), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1719] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(231), 1,
      anon_sym_else,
    ACTIONS(229), 6,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(227), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1744] = 11,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(195), 1,
      anon_sym_as,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_block,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1783] = 11,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(195), 1,
      anon_sym_as,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_block,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1822] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(237), 6,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(235), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1844] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(241), 6,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(239), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1866] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(93), 1,
      anon_sym_STAR,
    ACTIONS(95), 1,
      anon_sym_SLASH,
    ACTIONS(125), 1,
      anon_sym_AMP_AMP,
    ACTIONS(133), 1,
      anon_sym_PIPE_PIPE,
    ACTIONS(195), 1,
      anon_sym_as,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
    ACTIONS(109), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(115), 4,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1902] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(247), 6,
      anon_sym_LPAREN,
      anon_sym_RBRACE,
      anon_sym_DASH,
      anon_sym_BANG,
      sym_float_literal,
      sym_string_literal,
    ACTIONS(245), 8,
      anon_sym_let,
      anon_sym_if,
      anon_sym_while,
      anon_sym_return,
      sym_identifier,
      sym_integer_literal,
      anon_sym_true,
      anon_sym_false,
  [1924] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(7), 1,
      anon_sym_use,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    STATE(54), 2,
      sym_use_declaration,
      aux_sym_source_file_repeat1,
    STATE(56), 2,
      sym_function_definition,
      aux_sym_source_file_repeat2,
  [1945] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    STATE(69), 1,
      sym_type,
    ACTIONS(251), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_str,
  [1958] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    STATE(74), 1,
      sym_type,
    ACTIONS(251), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_str,
  [1971] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(255), 1,
      anon_sym_use,
    ACTIONS(253), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
    STATE(54), 2,
      sym_use_declaration,
      aux_sym_source_file_repeat1,
  [1986] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    STATE(18), 1,
      sym_type,
    ACTIONS(251), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_str,
  [1999] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(258), 1,
      ts_builtin_sym_end,
    STATE(57), 2,
      sym_function_definition,
      aux_sym_source_file_repeat2,
  [2013] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(260), 1,
      ts_builtin_sym_end,
    ACTIONS(262), 1,
      anon_sym_fn,
    STATE(57), 2,
      sym_function_definition,
      aux_sym_source_file_repeat2,
  [2027] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(9), 1,
      anon_sym_fn,
    ACTIONS(249), 1,
      ts_builtin_sym_end,
    STATE(57), 2,
      sym_function_definition,
      aux_sym_source_file_repeat2,
  [2041] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(265), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_parameter_list_repeat1,
  [2054] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(59), 1,
      aux_sym_parameter_list_repeat1,
  [2067] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(274), 3,
      ts_builtin_sym_end,
      anon_sym_use,
      anon_sym_fn,
  [2076] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
    ACTIONS(276), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      aux_sym_call_expression_repeat1,
  [2089] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(279), 1,
      sym_identifier,
    ACTIONS(281), 1,
      anon_sym_RPAREN,
    STATE(66), 1,
      sym_parameter,
  [2102] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(283), 1,
      anon_sym_DASH_GT,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_block,
  [2115] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(287), 1,
      anon_sym_RPAREN,
    STATE(62), 1,
      aux_sym_call_expression_repeat1,
  [2128] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(270), 1,
      anon_sym_COMMA,
    ACTIONS(289), 1,
      anon_sym_RPAREN,
    STATE(60), 1,
      aux_sym_parameter_list_repeat1,
  [2141] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(279), 1,
      sym_identifier,
    STATE(76), 1,
      sym_parameter,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(219), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [2159] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(285), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_block,
  [2169] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(291), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2177] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [2185] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(293), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [2193] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(233), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_block,
  [2203] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(295), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2211] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(297), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2219] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(268), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2227] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(299), 2,
      anon_sym_DASH_GT,
      anon_sym_LBRACE,
  [2235] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(301), 2,
      ts_builtin_sym_end,
      anon_sym_fn,
  [2243] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(303), 1,
      anon_sym_LPAREN,
    STATE(64), 1,
      sym_parameter_list,
  [2253] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(305), 1,
      sym_identifier,
  [2260] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(307), 1,
      anon_sym_EQ,
  [2267] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(309), 1,
      anon_sym_COLON,
  [2274] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(311), 1,
      sym_string_literal,
  [2281] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(313), 1,
      ts_builtin_sym_end,
  [2288] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(315), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 37,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 135,
  [SMALL_STATE(6)] = 196,
  [SMALL_STATE(7)] = 233,
  [SMALL_STATE(8)] = 272,
  [SMALL_STATE(9)] = 309,
  [SMALL_STATE(10)] = 370,
  [SMALL_STATE(11)] = 413,
  [SMALL_STATE(12)] = 474,
  [SMALL_STATE(13)] = 511,
  [SMALL_STATE(14)] = 548,
  [SMALL_STATE(15)] = 593,
  [SMALL_STATE(16)] = 630,
  [SMALL_STATE(17)] = 679,
  [SMALL_STATE(18)] = 740,
  [SMALL_STATE(19)] = 777,
  [SMALL_STATE(20)] = 828,
  [SMALL_STATE(21)] = 867,
  [SMALL_STATE(22)] = 906,
  [SMALL_STATE(23)] = 956,
  [SMALL_STATE(24)] = 1006,
  [SMALL_STATE(25)] = 1056,
  [SMALL_STATE(26)] = 1106,
  [SMALL_STATE(27)] = 1149,
  [SMALL_STATE(28)] = 1186,
  [SMALL_STATE(29)] = 1220,
  [SMALL_STATE(30)] = 1254,
  [SMALL_STATE(31)] = 1288,
  [SMALL_STATE(32)] = 1322,
  [SMALL_STATE(33)] = 1356,
  [SMALL_STATE(34)] = 1390,
  [SMALL_STATE(35)] = 1424,
  [SMALL_STATE(36)] = 1466,
  [SMALL_STATE(37)] = 1500,
  [SMALL_STATE(38)] = 1534,
  [SMALL_STATE(39)] = 1568,
  [SMALL_STATE(40)] = 1602,
  [SMALL_STATE(41)] = 1636,
  [SMALL_STATE(42)] = 1659,
  [SMALL_STATE(43)] = 1682,
  [SMALL_STATE(44)] = 1719,
  [SMALL_STATE(45)] = 1744,
  [SMALL_STATE(46)] = 1783,
  [SMALL_STATE(47)] = 1822,
  [SMALL_STATE(48)] = 1844,
  [SMALL_STATE(49)] = 1866,
  [SMALL_STATE(50)] = 1902,
  [SMALL_STATE(51)] = 1924,
  [SMALL_STATE(52)] = 1945,
  [SMALL_STATE(53)] = 1958,
  [SMALL_STATE(54)] = 1971,
  [SMALL_STATE(55)] = 1986,
  [SMALL_STATE(56)] = 1999,
  [SMALL_STATE(57)] = 2013,
  [SMALL_STATE(58)] = 2027,
  [SMALL_STATE(59)] = 2041,
  [SMALL_STATE(60)] = 2054,
  [SMALL_STATE(61)] = 2067,
  [SMALL_STATE(62)] = 2076,
  [SMALL_STATE(63)] = 2089,
  [SMALL_STATE(64)] = 2102,
  [SMALL_STATE(65)] = 2115,
  [SMALL_STATE(66)] = 2128,
  [SMALL_STATE(67)] = 2141,
  [SMALL_STATE(68)] = 2151,
  [SMALL_STATE(69)] = 2159,
  [SMALL_STATE(70)] = 2169,
  [SMALL_STATE(71)] = 2177,
  [SMALL_STATE(72)] = 2185,
  [SMALL_STATE(73)] = 2193,
  [SMALL_STATE(74)] = 2203,
  [SMALL_STATE(75)] = 2211,
  [SMALL_STATE(76)] = 2219,
  [SMALL_STATE(77)] = 2227,
  [SMALL_STATE(78)] = 2235,
  [SMALL_STATE(79)] = 2243,
  [SMALL_STATE(80)] = 2253,
  [SMALL_STATE(81)] = 2260,
  [SMALL_STATE(82)] = 2267,
  [SMALL_STATE(83)] = 2274,
  [SMALL_STATE(84)] = 2281,
  [SMALL_STATE(85)] = 2288,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 3, 0, 9),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 3, 0, 9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_expression, 2, 0, 6),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 6),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 5, 0, 9),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 5, 0, 9),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_expression, 3, 0, 11),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 11),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 9),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 9),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cast_expression, 3, 0, 12),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cast_expression, 3, 0, 12),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment_statement, 3, 0, 10),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment_statement, 3, 0, 10),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_statement, 4, 0, 13),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_statement, 4, 0, 13),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 2, 0, 5),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 2, 0, 5),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return_statement, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_return_statement, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [165] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 3, 0, 7),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 3, 0, 7),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [239] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 14),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 14),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_while_statement, 3, 0, 8),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_statement, 3, 0, 8),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(83),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(85),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_use_declaration, 2, 0, 1),
  [276] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_call_expression_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 3, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 2),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 3, 0, 3),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 4, 0, 0),
  [301] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 4),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [313] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_beer(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
